# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jretter <jretter@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/12 17:02:02 by jretter           #+#    #+#              #
#    Updated: 2024/12/18 15:34:01 by jretter          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Explanation:
# Variables:

# NAME: The name of your final program or library.
# CC: The compiler, typically cc.
# CFLAGS: The compiler flags that include -Wall -Wextra -Werror.
# SRCS: Source files, here it assumes main.c and all ft_*.c files.
# OBJS: Object files, automatically generated by replacing .c with .o.
# LIBFT: Path to the compiled libft.a library, if used.
# Rules:

# all: Default target that builds the program using the object files and libft.a.
# $(NAME): Links the object files to create the final executable.
# $(LIBFT): Compiles the libft library by navigating to its folder and running make.
# clean: Removes object files.
# fclean: Removes both object files and the compiled program/library.
# re: Cleans everything and recompiles from scratch.

NAME = so_long
CC = cc
CFLAGS = -Wall -Wextra -Werror
SRCS = so_long.c validate_map.c render.c player.c keypress.c validate.c floodfill.c getnextline.c clean.c
OBJS = $(SRCS:.c=.o)
LIBFT = libft/libft.a
MLX42 = MLX42/build/libmlx42.a
INCLUDES = -IMLX42/include -Ilibft
USER = $(shell brew --prefix glfw)/lib/

# MLX42 Flags
MLX_FLAGS = -L"$(USER)" -lglfw -framework Cocoa -framework OpenGL -framework IOKit

# Default target
all: $(NAME)

# Build the executable
$(NAME): $(OBJS) $(LIBFT) $(MLX42)
	$(CC) $(CFLAGS) $(OBJS) $(LIBFT) $(MLX42) $(MLX_FLAGS) -o $(NAME)

# Build the libft library
$(LIBFT):
	@echo "Building libft..."
	make -C libft

# Build MLX42 Library
$(MLX42):
	@echo "Building MLX42 library..."
	cmake -S MLX42 -B MLX42/build
	cmake --build MLX42/build

# Pattern rule for compiling .c to .o
.c.o:
	$(CC) $(CFLAGS) -c -o $@ $< $(INCLUDES)

# Clean up object files
clean:
	rm -f $(OBJS)
	make -C libft clean

# Clean up all build files
fclean: clean
	rm -f $(NAME)
	make -C libft fclean

# Rebuild everything
re: fclean all

# Phony targets
.PHONY: all clean fclean re




